### PR TITLE
React 16

### PR DESCRIPTION
**Pull request by export-mike**
After feedback in the [previous PR](https://github.com/gvaldambrini/storybook-router/pull/18) I've created a new branch off master,

- To me Resolving to RR3 and RR4 in a single version of this library comes with a whole bunch of complexity. 
  - we have to use different scripts to run the storybook in different modes.
  - we also have to write imperative logic to check for null exports from react router to determine what version we're running with. 
  
This PR removes support for V3 of RR and also adds React 16 support.

### CODE REVIEW

**Comment by gvaldambrini** [comment]
Hi @export-mike, again thank you for your interest and help. However, even if I agree that in most cases adding a link to an old npm version for RR3 can be enough, I cannot see a valid reason to break the compatibility atm. Imo this is especially true because:
 - there are still a lot of people using RR3, and I want to offer them bugfixes if necessary;
 - there isn't a refactoring of the React code required for this task or the foreseeable future, and the complexity required to support RR3 does not hurt at all.

To summarize this pr and the #18 old one:
 - I'd like to use peerDependencies to support React 16 and react-router v3 + v4, taking also into account Vue.js (I cannot see a big deal in an additional dependency, but it must stay compatible);
- there is still the problem of the nonworking `npm link` to investigate that makes every release harder to test;
- I'm fine to just update the dependency to React for now.

Would you mind updating this pr so that RR3 is still supported? Let me know if I forgot or misunderstood something. Thanks!

**Comment by export-mike** [comment]
hi @gvaldambrini I don't understand how its possible to have react router 3 and 4 specified in the same package.json. I have pushed a couple of example projects that use rr3 and rr4. https://github.com/export-mike/storybook-router-examples/tree/master

Please take a look. Thanks

**Comment by gvaldambrini** [comment]
Hi @export-mike, thanks for your help in investigating this problem. You're right, the demo project you've created shown there is a problem with the dependencies.  As far as I understand, the solution for the react-router v3 and v4 problem would be using the peerDependencies. I pushed a version that moves react + react-router and vue + vue-router in the peerDependencies. You can find it in the branch https://github.com/gvaldambrini/storybook-router/tree/r16 which contains also the dist folder so that you can add it to the package.json like this:
```
"storybook-router": "git+https://git@github.com/gvaldambrini/storybook-router.git#r16"
```
Everything seems fine, and in the tests I performed I was able to use react-router v3 and v4. The problem arises with the vue based demo-project that, even if it's specular to the react one, complains about an unresolved module `react-router`. 
I'm investigating the problem but of course any idea would be appreciated.

**Comment by export-mike** [comment]
I'd still push to having a RR3 version and two packages, this way less chances of implementations getting in the way of each other in the future.

```storybook-vue-router```
```storybook-react-router```

by the sounds of things not many people are using this library with RR3 as there would be an issue for supporting RR3.

**Comment by gvaldambrini** [comment]
In the end, even if I'm quite disappointed, I think I'll split the package in 2 version, one for react and the other for vue. With that we can use peerDependencies to still continue supporting RR3 and remove all the issues. I'll let you know as soon as I have something to try (of course any feedback is welcomed).

**Comment by export-mike** [comment]
I think this is the best way to go its the simplest approach. KISS (Keep it simple stupid) happy to help with the new structure :) I'll submit a PR this week

**Comment by gvaldambrini** [comment]
Ok, wonderful. Thank in advance you for your help. Please consider that I'd like to maintain a single repository so currently I'm thinking about solutions like lerna (but I'm open to equivalent solutions).

**Comment by export-mike** [comment]
Exactly. we could even experiment with james kyles latest project bolt.
http://boltpkg.com/

**Comment by ndelangen** [comment]
Over at storybook we use yarn and yarn workspaces, and are quite happy with it.

If you do decide to try bolt and have think it would benefit the storybook monorepo, please let us know? ♥️

**Comment by export-mike** [comment]
@gvaldambrini I've been too caught up in the festivities. will hopefully submit a PR soon, I see it being a good experiment to try something new

**Comment by gvaldambrini** [comment]
@export-mike ok, no problem. Thanks for letting me know!

**Comment by gvaldambrini** [comment]
@export-mike any news on that? Are you still interested in creating a PR for this issue?

**Comment by export-mike** [comment]
@gvaldambrini hey I have the beggining stages to use bolt,

**Comment by export-mike** [comment]
https://github.com/export-mike/storybook-router/tree/bolt @gvaldambrini

**Comment by gvaldambrini** [comment]
@export-mike thanks! I'll have a detailed look asap, in the meanwhile please try to change the bare minimum in order to split the code in two packages in this pr, as I'd like to test very carefully potential regressions.

**Comment by gvaldambrini** [comment]
@export-mike what is the status of this task? I'd like to wrap up this split task in February. Do you have time to do this? Otherwise I can start from your branch and wrap it up by myself. Please let me know.

**Comment by ecbrodie** [comment]
Any updates on the status of this PR?

My project is on version 0.3.2 and now all of the project devs need to condition themselves to ignore a long, loud warning in our test suite about ` You are running Vue in development mode.` (plus many other lines of stack trace) on our React project. I am tempted to downgrade until `storybook-router` has been split into two packages, but that seems like a risky move for me to make.

**Comment by gvaldambrini** [comment]
Hi @export-mike, did you have any chance to work on this? I'm sorry, but I want to complete this work asap so this week I'm going to do this by myself unless you can wrap this up. Please let us know.

**Comment by export-mike** [comment]
Hi gianni I’m not going to be able to help

**Comment by ecbrodie** [comment]
@gvaldambrini why was this closed? Are you still going to complete this work, like you said said would be done 23 days ago when @export-mike indicated he is no longer going to be able to help? Or is this project going to be taking a different direction?

**Comment by gvaldambrini** [comment]
@ecbrodie I'm working on this and hopefully in few days it will be ready. But I chose a slightly different direction, using lerna to split the repo in multiple packages (and so I'm not going to reuse anything written or linked here). 😄

**Pull request closed without merging**
